version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: usdx
      POSTGRES_PASSWORD: usdxpassword
      POSTGRES_DB: usdx_wexel
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  pg_data:
  redis_data:
